import { Inter } from "next/font/google";

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0 }}>
        <GoogleOAuthProvider
            clientId="504897621923-epbrurgigh04jv448bnit08lh1nnifoa.apps.googleusercontent.com"
        >
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
